### ISSUE TITLE
Список ToDo

### ISSUE THREAD

**Issue by niqzart** [xi-effect/xi.backend#91]
## Описание
Простой список заданий, в котором пользователь может размечать задания для себя на день. Складывать в `xieffect/communities/services/todo_*.py`. Стоит сделать в два захода: сначала БД и ReST, затем апдейт БД, ReST и добавление SIO. На каждом этапе пробовать писать тесты, можно в комплекте с остальным (т.е. давать на ревью первую часть с тестами, затем вторую часть тоже с тестами) или же теперь уже в четыре захода (т.е. давать на ревью первую часть, потом тесты, затем вторую часть и потом тесты)

### Одна таблица, что-то вроде `Task`, содержащая:
- id задания
- id создателя задания (для разрешения редактирования/удаления)
- категория (строка пока что)
- название (строка, задаётся пользователем)
- дата-время
- длительность

### Вторая таблица, соединяющая Many To Many пользователей с тасками:
- id user-а, PK
- id task-и, PK

*M2M отношение тут для того, чтобы БД была future-proof, ведь задачи в будущем будут отражать и уроки, например, которые будут отображаться сразу у многих учеников.*

### Попытка один: чистый ReST
- [ ] Создание задания пользователем (создаёт таску в первой и привязывает во второй таблице)
- [ ] Редактирование задания (проверка владения, изменение любых полей, не обязательно клиента заставлять вводить всё)
- [ ] Удаление задания (проверка владения, удалиние из обеих таблиц, во втором может быть много записей!)
- [ ] Нахождение списка заданий (пагинация, клиент может ввести дату, default = текущая дата)

### Попытка два: немного SIO
- [ ] Перенести создание, редактирование и удаление в SIO
- [ ] Эмитить ивенты для комнаты user-<id>
- [ ] Исключить отправителя и возвращать ack-и

# Deprecated
Должа быть возможность создавать как одиночные задания, так и повторяющиеся. Желательно использовать rfc5545, секция 3.3.10

## Полезные ссылки
- [стандарт](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.10)
- [библиотека python](https://dateutil.readthedocs.io/en/stable/)
- [аналог для JS](https://github.com/jakubroztocil/rrule) (чтобы понимать, что может фронт)
